In [8]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import pickle

In [5]:
# loading the dataset
data=pd.read_csv('C:/Users/user/Documents/Machine Learning/dft-road-casualty-statistics-collision-2023.csv')
data.tail(10)

C:\Users\user\AppData\Local\Temp\ipykernel_20224\1244585395.py:2: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  accidents=pd.read_csv('C:/Users/user/Documents/Machine Learning/dft-road-casualty-statistics-collision-2023.csv')

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,...,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision
104248,2023991444794,2023,991444794,247981.0,636823.0,-4.414422,55.601214,99,2,1,...,6,2,2,0,0,2,1,-1,-1,7
104249,2023991445470,2023,991445470,325949.0,676194.0,-3.188075,55.973007,99,2,1,...,4,1,2,-1,-1,1,1,-1,-1,7
104250,2023991445738,2023,991445738,252810.0,667775.0,-4.354530,55.880571,99,3,3,...,1,1,1,-1,-1,1,1,-1,-1,3
104251,2023991450226,2023,991450226,283129.0,681586.0,-3.876173,56.012907,99,3,2,...,1,1,1,-1,-1,2,1,-1,-1,3
104252,2023991451985,2023,991451985,293749.0,679120.0,-3.704944,55.993233,99,3,2,...,6,1,1,0,0,1,1,-1,-1,3
104253,2023991452286,2023,991452286,246754.0,661133.0,-4.447490,55.819059,99,2,1,...,5,2,2,-1,-1,1,1,-1,-1,7
104254,2023991452640,2023,991452640,224491.0,581627.0,-4.752200,55.097920,99,3,2,...,1,9,1,0,0,2,2,-1,-1,3
104255,2023991453360,2023,991453360,383341.0,806427.0,-2.276957,57.148422,99,3,2,...,4,2,2,-1,-1,1,1,-1,-1,3
104256,2023991461915,2023,991461915,271662.0,655488.0,-4.047591,55.775637,99,3,1,...,4,8,1,-1,-1,1,1,-1,-1,3
104257,2023991462793,2023,991462793,327349.0,666746.0,-3.163102,55.888350,99,3,2,...,1,1,1,0,0,2,1,-1,-1,3

In [ ]:
# Target variable
y = data['casualty_severity']

In [ ]:
# Independent variables
X = data[['casualty_class', 'sex_of_casualty', 'age_of_casualty', 
          'age_band_of_casualty', 'pedestrian_location', 'pedestrian_movement',
          'car_passenger', 'bus_or_coach_passenger', 'casualty_type', 
          'casualty_home_area_type', 'casualty_imd_decile']]

In [ ]:
# Handle missing values by filling them with the mean of each column
X.fillna(X.mean(), inplace=True)

In [ ]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

In [ ]:
# Predictions and evaluation
y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Model Evaluation:")
print("Mean Squared Error:", mse)
print("R-squared:", r2)

In [ ]:
#Saving model
model.save()